/**
 * Stage 1 リグレッションテスト用フィクスチャ。
 *
 * **このファイルは自動生成されている。直接編集しないこと。**
 * 再生成: cd apps/chrome-ext && pnpm exec tsx scripts/generate-stage1-fixtures.ts
 *
 * 期待値は filter.ts (apps/chrome-ext/src/content) を直接実行して取得した値を
 * 静的に埋め込んでいる。判定エンジン側のテストは apps/chrome-ext を参照しない。
 *
 * 合計 61 件（A:21 B:6 C:10 D:5 E:5 F:5 G:6 H:3）
 */

import type { MatchResult } from './stage1-types.js';

// ─── A. matchesKeyword ──────────────────────────────────────────────
export interface MatchesKeywordFixture {
  name: string;
  /** 該当フィクスチャの背景・意図（複合ケースの解説等） */
  comment?: string;
  input: { text: string; keywords: string[]; descriptionPhrases: string[] };
  expected: MatchResult | null;
}

export const MATCHES_KEYWORD_FIXTURES: MatchesKeywordFixture[] = [
  {
    "name": "パターン1: ネタバレ単語そのまま",
    "input": {
      "text": "これネタバレですか？",
      "keywords": [
        "高日",
        "高日美佳",
        "Cindy Stone",
        "Cindy",
        "被害者",
        "山野",
        "山野星雄",
        "Frank Sahwit",
        "Sahwit",
        "犯人",
        "綾里千尋",
        "千尋",
        "Mia Fey",
        "Mia",
        "死んだ",
        "殺された",
        "小中",
        "小中大",
        "Redd White",
        "ブルーコープ",
        "Bluecorp",
        "綾里真宵",
        "真宵",
        "Maya Fey",
        "Maya",
        "逮捕",
        "容疑者",
        "口寄せ",
        "霊媒",
        "霊術",
        "channeling",
        "spirit channeling",
        "千尋を呼ぶ",
        "荷星",
        "荷星三郎",
        "Will Powers",
        "トノサマン",
        "被告",
        "衣袋",
        "衣袋武志",
        "Jack Hammer",
        "Hammer",
        "元俳優",
        "姫神",
        "姫神サクラ",
        "Dee Vasquez",
        "プロデューサー",
        "マフィア",
        "5年前",
        "事故",
        "スタジオ",
        "グローバルスタジオ",
        "Global Studios",
        "狩魔",
        "狩魔豪",
        "Manfred von Karma",
        "von Karma",
        "フォン・カルマ",
        "DL-6",
        "DL6",
        "15年前",
        "真相",
        "御剣信",
        "Gregory Edgeworth",
        "エレベーター",
        "生倉",
        "生倉雪夫",
        "Robert Hammond",
        "Hammond",
        "悪徳弁護士",
        "湖",
        "灰根",
        "灰根高太郎",
        "Yanni Yogi",
        "Yogi",
        "管理人",
        "怜侍の父",
        "弁護士",
        "射殺",
        "狩魔に殺された",
        "怜侍",
        "御剣",
        "トラウマ",
        "父を殺した",
        "地震",
        "銃",
        "多田敷",
        "多田敷道夫",
        "Bruce Goodman",
        "Goodman",
        "刑事",
        "宝月巴",
        "宝月",
        "Lana Skye",
        "Lana",
        "検事正",
        "巌徒",
        "巌徒海慈",
        "Damon Gant",
        "Gant",
        "署長",
        "警察署長",
        "SL-9",
        "SL9",
        "2年前",
        "証拠改ざん",
        "罪門直斗",
        "罪門",
        "Neil Marshall",
        "Neil",
        "青影",
        "青影丈",
        "Joe Darke",
        "Darke",
        "連続殺人犯",
        "宝月茜",
        "Ema Skye",
        "Ema",
        "科学捜査",
        "霊",
        "真宵から千尋",
        "Edgeworth",
        "協力",
        "改心",
        "変わった",
        "未解決事件",
        "御剣の過去",
        "因縁",
        "宿敵",
        "弟子",
        "助手",
        "パートナー",
        "綾里事務所"
      ],
      "descriptionPhrases": [
        "DL-6号事件",
        "SL-9号事件",
        "DL-6"
      ]
    },
    "expected": {
      "reason": "spoiler_word"
    }
  },
  {
    "name": "パターン1: ひらがな「ねたばれ」（カナ正規化）",
    "input": {
      "text": "ねたばれ注意",
      "keywords": [
        "高日",
        "高日美佳",
        "Cindy Stone",
        "Cindy",
        "被害者",
        "山野",
        "山野星雄",
        "Frank Sahwit",
        "Sahwit",
        "犯人",
        "綾里千尋",
        "千尋",
        "Mia Fey",
        "Mia",
        "死んだ",
        "殺された",
        "小中",
        "小中大",
        "Redd White",
        "ブルーコープ",
        "Bluecorp",
        "綾里真宵",
        "真宵",
        "Maya Fey",
        "Maya",
        "逮捕",
        "容疑者",
        "口寄せ",
        "霊媒",
        "霊術",
        "channeling",
        "spirit channeling",
        "千尋を呼ぶ",
        "荷星",
        "荷星三郎",
        "Will Powers",
        "トノサマン",
        "被告",
        "衣袋",
        "衣袋武志",
        "Jack Hammer",
        "Hammer",
        "元俳優",
        "姫神",
        "姫神サクラ",
        "Dee Vasquez",
        "プロデューサー",
        "マフィア",
        "5年前",
        "事故",
        "スタジオ",
        "グローバルスタジオ",
        "Global Studios",
        "狩魔",
        "狩魔豪",
        "Manfred von Karma",
        "von Karma",
        "フォン・カルマ",
        "DL-6",
        "DL6",
        "15年前",
        "真相",
        "御剣信",
        "Gregory Edgeworth",
        "エレベーター",
        "生倉",
        "生倉雪夫",
        "Robert Hammond",
        "Hammond",
        "悪徳弁護士",
        "湖",
        "灰根",
        "灰根高太郎",
        "Yanni Yogi",
        "Yogi",
        "管理人",
        "怜侍の父",
        "弁護士",
        "射殺",
        "狩魔に殺された",
        "怜侍",
        "御剣",
        "トラウマ",
        "父を殺した",
        "地震",
        "銃",
        "多田敷",
        "多田敷道夫",
        "Bruce Goodman",
        "Goodman",
        "刑事",
        "宝月巴",
        "宝月",
        "Lana Skye",
        "Lana",
        "検事正",
        "巌徒",
        "巌徒海慈",
        "Damon Gant",
        "Gant",
        "署長",
        "警察署長",
        "SL-9",
        "SL9",
        "2年前",
        "証拠改ざん",
        "罪門直斗",
        "罪門",
        "Neil Marshall",
        "Neil",
        "青影",
        "青影丈",
        "Joe Darke",
        "Darke",
        "連続殺人犯",
        "宝月茜",
        "Ema Skye",
        "Ema",
        "科学捜査",
        "霊",
        "真宵から千尋",
        "Edgeworth",
        "協力",
        "改心",
        "変わった",
        "未解決事件",
        "御剣の過去",
        "因縁",
        "宿敵",
        "弟子",
        "助手",
        "パートナー",
        "綾里事務所"
      ],
      "descriptionPhrases": [
        "DL-6号事件",
        "SL-9号事件",
        "DL-6"
      ]
    },
    "expected": {
      "reason": "spoiler_word"
    }
  },
  {
    "name": "パターン1: ネタバレ含むコンテキスト長文",
    "input": {
      "text": "いやー、これ完全にネタバレ食らった気分です",
      "keywords": [
        "高日",
        "高日美佳",
        "Cindy Stone",
        "Cindy",
        "被害者",
        "山野",
        "山野星雄",
        "Frank Sahwit",
        "Sahwit",
        "犯人",
        "綾里千尋",
        "千尋",
        "Mia Fey",
        "Mia",
        "死んだ",
        "殺された",
        "小中",
        "小中大",
        "Redd White",
        "ブルーコープ",
        "Bluecorp",
        "綾里真宵",
        "真宵",
        "Maya Fey",
        "Maya",
        "逮捕",
        "容疑者",
        "口寄せ",
        "霊媒",
        "霊術",
        "channeling",
        "spirit channeling",
        "千尋を呼ぶ",
        "荷星",
        "荷星三郎",
        "Will Powers",
        "トノサマン",
        "被告",
        "衣袋",
        "衣袋武志",
        "Jack Hammer",
        "Hammer",
        "元俳優",
        "姫神",
        "姫神サクラ",
        "Dee Vasquez",
        "プロデューサー",
        "マフィア",
        "5年前",
        "事故",
        "スタジオ",
        "グローバルスタジオ",
        "Global Studios",
        "狩魔",
        "狩魔豪",
        "Manfred von Karma",
        "von Karma",
        "フォン・カルマ",
        "DL-6",
        "DL6",
        "15年前",
        "真相",
        "御剣信",
        "Gregory Edgeworth",
        "エレベーター",
        "生倉",
        "生倉雪夫",
        "Robert Hammond",
        "Hammond",
        "悪徳弁護士",
        "湖",
        "灰根",
        "灰根高太郎",
        "Yanni Yogi",
        "Yogi",
        "管理人",
        "怜侍の父",
        "弁護士",
        "射殺",
        "狩魔に殺された",
        "怜侍",
        "御剣",
        "トラウマ",
        "父を殺した",
        "地震",
        "銃",
        "多田敷",
        "多田敷道夫",
        "Bruce Goodman",
        "Goodman",
        "刑事",
        "宝月巴",
        "宝月",
        "Lana Skye",
        "Lana",
        "検事正",
        "巌徒",
        "巌徒海慈",
        "Damon Gant",
        "Gant",
        "署長",
        "警察署長",
        "SL-9",
        "SL9",
        "2年前",
        "証拠改ざん",
        "罪門直斗",
        "罪門",
        "Neil Marshall",
        "Neil",
        "青影",
        "青影丈",
        "Joe Darke",
        "Darke",
        "連続殺人犯",
        "宝月茜",
        "Ema Skye",
        "Ema",
        "科学捜査",
        "霊",
        "真宵から千尋",
        "Edgeworth",
        "協力",
        "改心",
        "変わった",
        "未解決事件",
        "御剣の過去",
        "因縁",
        "宿敵",
        "弟子",
        "助手",
        "パートナー",
        "綾里事務所"
      ],
      "descriptionPhrases": [
        "DL-6号事件",
        "SL-9号事件",
        "DL-6"
      ]
    },
    "expected": {
      "reason": "spoiler_word"
    }
  },
  {
    "name": "パターン2: DL-6号事件",
    "input": {
      "text": "DL-6号事件って何",
      "keywords": [
        "高日",
        "高日美佳",
        "Cindy Stone",
        "Cindy",
        "被害者",
        "山野",
        "山野星雄",
        "Frank Sahwit",
        "Sahwit",
        "犯人",
        "綾里千尋",
        "千尋",
        "Mia Fey",
        "Mia",
        "死んだ",
        "殺された",
        "小中",
        "小中大",
        "Redd White",
        "ブルーコープ",
        "Bluecorp",
        "綾里真宵",
        "真宵",
        "Maya Fey",
        "Maya",
        "逮捕",
        "容疑者",
        "口寄せ",
        "霊媒",
        "霊術",
        "channeling",
        "spirit channeling",
        "千尋を呼ぶ",
        "荷星",
        "荷星三郎",
        "Will Powers",
        "トノサマン",
        "被告",
        "衣袋",
        "衣袋武志",
        "Jack Hammer",
        "Hammer",
        "元俳優",
        "姫神",
        "姫神サクラ",
        "Dee Vasquez",
        "プロデューサー",
        "マフィア",
        "5年前",
        "事故",
        "スタジオ",
        "グローバルスタジオ",
        "Global Studios",
        "狩魔",
        "狩魔豪",
        "Manfred von Karma",
        "von Karma",
        "フォン・カルマ",
        "DL-6",
        "DL6",
        "15年前",
        "真相",
        "御剣信",
        "Gregory Edgeworth",
        "エレベーター",
        "生倉",
        "生倉雪夫",
        "Robert Hammond",
        "Hammond",
        "悪徳弁護士",
        "湖",
        "灰根",
        "灰根高太郎",
        "Yanni Yogi",
        "Yogi",
        "管理人",
        "怜侍の父",
        "弁護士",
        "射殺",
        "狩魔に殺された",
        "怜侍",
        "御剣",
        "トラウマ",
        "父を殺した",
        "地震",
        "銃",
        "多田敷",
        "多田敷道夫",
        "Bruce Goodman",
        "Goodman",
        "刑事",
        "宝月巴",
        "宝月",
        "Lana Skye",
        "Lana",
        "検事正",
        "巌徒",
        "巌徒海慈",
        "Damon Gant",
        "Gant",
        "署長",
        "警察署長",
        "SL-9",
        "SL9",
        "2年前",
        "証拠改ざん",
        "罪門直斗",
        "罪門",
        "Neil Marshall",
        "Neil",
        "青影",
        "青影丈",
        "Joe Darke",
        "Darke",
        "連続殺人犯",
        "宝月茜",
        "Ema Skye",
        "Ema",
        "科学捜査",
        "霊",
        "真宵から千尋",
        "Edgeworth",
        "協力",
        "改心",
        "変わった",
        "未解決事件",
        "御剣の過去",
        "因縁",
        "宿敵",
        "弟子",
        "助手",
        "パートナー",
        "綾里事務所"
      ],
      "descriptionPhrases": [
        "DL-6号事件",
        "SL-9号事件",
        "DL-6"
      ]
    },
    "expected": {
      "reason": "description_phrase",
      "phrase": "DL-6号事件"
    }
  },
  {
    "name": "パターン2: SL-9号事件",
    "input": {
      "text": "SL-9号事件のラスボスやばい",
      "keywords": [
        "高日",
        "高日美佳",
        "Cindy Stone",
        "Cindy",
        "被害者",
        "山野",
        "山野星雄",
        "Frank Sahwit",
        "Sahwit",
        "犯人",
        "綾里千尋",
        "千尋",
        "Mia Fey",
        "Mia",
        "死んだ",
        "殺された",
        "小中",
        "小中大",
        "Redd White",
        "ブルーコープ",
        "Bluecorp",
        "綾里真宵",
        "真宵",
        "Maya Fey",
        "Maya",
        "逮捕",
        "容疑者",
        "口寄せ",
        "霊媒",
        "霊術",
        "channeling",
        "spirit channeling",
        "千尋を呼ぶ",
        "荷星",
        "荷星三郎",
        "Will Powers",
        "トノサマン",
        "被告",
        "衣袋",
        "衣袋武志",
        "Jack Hammer",
        "Hammer",
        "元俳優",
        "姫神",
        "姫神サクラ",
        "Dee Vasquez",
        "プロデューサー",
        "マフィア",
        "5年前",
        "事故",
        "スタジオ",
        "グローバルスタジオ",
        "Global Studios",
        "狩魔",
        "狩魔豪",
        "Manfred von Karma",
        "von Karma",
        "フォン・カルマ",
        "DL-6",
        "DL6",
        "15年前",
        "真相",
        "御剣信",
        "Gregory Edgeworth",
        "エレベーター",
        "生倉",
        "生倉雪夫",
        "Robert Hammond",
        "Hammond",
        "悪徳弁護士",
        "湖",
        "灰根",
        "灰根高太郎",
        "Yanni Yogi",
        "Yogi",
        "管理人",
        "怜侍の父",
        "弁護士",
        "射殺",
        "狩魔に殺された",
        "怜侍",
        "御剣",
        "トラウマ",
        "父を殺した",
        "地震",
        "銃",
        "多田敷",
        "多田敷道夫",
        "Bruce Goodman",
        "Goodman",
        "刑事",
        "宝月巴",
        "宝月",
        "Lana Skye",
        "Lana",
        "検事正",
        "巌徒",
        "巌徒海慈",
        "Damon Gant",
        "Gant",
        "署長",
        "警察署長",
        "SL-9",
        "SL9",
        "2年前",
        "証拠改ざん",
        "罪門直斗",
        "罪門",
        "Neil Marshall",
        "Neil",
        "青影",
        "青影丈",
        "Joe Darke",
        "Darke",
        "連続殺人犯",
        "宝月茜",
        "Ema Skye",
        "Ema",
        "科学捜査",
        "霊",
        "真宵から千尋",
        "Edgeworth",
        "協力",
        "改心",
        "変わった",
        "未解決事件",
        "御剣の過去",
        "因縁",
        "宿敵",
        "弟子",
        "助手",
        "パートナー",
        "綾里事務所"
      ],
      "descriptionPhrases": [
        "DL-6号事件",
        "SL-9号事件",
        "DL-6"
      ]
    },
    "expected": {
      "reason": "description_phrase",
      "phrase": "SL-9号事件"
    }
  },
  {
    "name": "パターン2: 該当しない一般文",
    "input": {
      "text": "これ普通のコメントですよ",
      "keywords": [
        "高日",
        "高日美佳",
        "Cindy Stone",
        "Cindy",
        "被害者",
        "山野",
        "山野星雄",
        "Frank Sahwit",
        "Sahwit",
        "犯人",
        "綾里千尋",
        "千尋",
        "Mia Fey",
        "Mia",
        "死んだ",
        "殺された",
        "小中",
        "小中大",
        "Redd White",
        "ブルーコープ",
        "Bluecorp",
        "綾里真宵",
        "真宵",
        "Maya Fey",
        "Maya",
        "逮捕",
        "容疑者",
        "口寄せ",
        "霊媒",
        "霊術",
        "channeling",
        "spirit channeling",
        "千尋を呼ぶ",
        "荷星",
        "荷星三郎",
        "Will Powers",
        "トノサマン",
        "被告",
        "衣袋",
        "衣袋武志",
        "Jack Hammer",
        "Hammer",
        "元俳優",
        "姫神",
        "姫神サクラ",
        "Dee Vasquez",
        "プロデューサー",
        "マフィア",
        "5年前",
        "事故",
        "スタジオ",
        "グローバルスタジオ",
        "Global Studios",
        "狩魔",
        "狩魔豪",
        "Manfred von Karma",
        "von Karma",
        "フォン・カルマ",
        "DL-6",
        "DL6",
        "15年前",
        "真相",
        "御剣信",
        "Gregory Edgeworth",
        "エレベーター",
        "生倉",
        "生倉雪夫",
        "Robert Hammond",
        "Hammond",
        "悪徳弁護士",
        "湖",
        "灰根",
        "灰根高太郎",
        "Yanni Yogi",
        "Yogi",
        "管理人",
        "怜侍の父",
        "弁護士",
        "射殺",
        "狩魔に殺された",
        "怜侍",
        "御剣",
        "トラウマ",
        "父を殺した",
        "地震",
        "銃",
        "多田敷",
        "多田敷道夫",
        "Bruce Goodman",
        "Goodman",
        "刑事",
        "宝月巴",
        "宝月",
        "Lana Skye",
        "Lana",
        "検事正",
        "巌徒",
        "巌徒海慈",
        "Damon Gant",
        "Gant",
        "署長",
        "警察署長",
        "SL-9",
        "SL9",
        "2年前",
        "証拠改ざん",
        "罪門直斗",
        "罪門",
        "Neil Marshall",
        "Neil",
        "青影",
        "青影丈",
        "Joe Darke",
        "Darke",
        "連続殺人犯",
        "宝月茜",
        "Ema Skye",
        "Ema",
        "科学捜査",
        "霊",
        "真宵から千尋",
        "Edgeworth",
        "協力",
        "改心",
        "変わった",
        "未解決事件",
        "御剣の過去",
        "因縁",
        "宿敵",
        "弟子",
        "助手",
        "パートナー",
        "綾里事務所"
      ],
      "descriptionPhrases": [
        "DL-6号事件",
        "SL-9号事件",
        "DL-6"
      ]
    },
    "expected": null
  },
  {
    "name": "パターン3: 高日が死んだ（KW+動詞）",
    "input": {
      "text": "高日が死んだのか",
      "keywords": [
        "高日",
        "高日美佳",
        "Cindy Stone",
        "Cindy",
        "被害者",
        "山野",
        "山野星雄",
        "Frank Sahwit",
        "Sahwit",
        "犯人",
        "綾里千尋",
        "千尋",
        "Mia Fey",
        "Mia",
        "死んだ",
        "殺された",
        "小中",
        "小中大",
        "Redd White",
        "ブルーコープ",
        "Bluecorp",
        "綾里真宵",
        "真宵",
        "Maya Fey",
        "Maya",
        "逮捕",
        "容疑者",
        "口寄せ",
        "霊媒",
        "霊術",
        "channeling",
        "spirit channeling",
        "千尋を呼ぶ",
        "荷星",
        "荷星三郎",
        "Will Powers",
        "トノサマン",
        "被告",
        "衣袋",
        "衣袋武志",
        "Jack Hammer",
        "Hammer",
        "元俳優",
        "姫神",
        "姫神サクラ",
        "Dee Vasquez",
        "プロデューサー",
        "マフィア",
        "5年前",
        "事故",
        "スタジオ",
        "グローバルスタジオ",
        "Global Studios",
        "狩魔",
        "狩魔豪",
        "Manfred von Karma",
        "von Karma",
        "フォン・カルマ",
        "DL-6",
        "DL6",
        "15年前",
        "真相",
        "御剣信",
        "Gregory Edgeworth",
        "エレベーター",
        "生倉",
        "生倉雪夫",
        "Robert Hammond",
        "Hammond",
        "悪徳弁護士",
        "湖",
        "灰根",
        "灰根高太郎",
        "Yanni Yogi",
        "Yogi",
        "管理人",
        "怜侍の父",
        "弁護士",
        "射殺",
        "狩魔に殺された",
        "怜侍",
        "御剣",
        "トラウマ",
        "父を殺した",
        "地震",
        "銃",
        "多田敷",
        "多田敷道夫",
        "Bruce Goodman",
        "Goodman",
        "刑事",
        "宝月巴",
        "宝月",
        "Lana Skye",
        "Lana",
        "検事正",
        "巌徒",
        "巌徒海慈",
        "Damon Gant",
        "Gant",
        "署長",
        "警察署長",
        "SL-9",
        "SL9",
        "2年前",
        "証拠改ざん",
        "罪門直斗",
        "罪門",
        "Neil Marshall",
        "Neil",
        "青影",
        "青影丈",
        "Joe Darke",
        "Darke",
        "連続殺人犯",
        "宝月茜",
        "Ema Skye",
        "Ema",
        "科学捜査",
        "霊",
        "真宵から千尋",
        "Edgeworth",
        "協力",
        "改心",
        "変わった",
        "未解決事件",
        "御剣の過去",
        "因縁",
        "宿敵",
        "弟子",
        "助手",
        "パートナー",
        "綾里事務所"
      ],
      "descriptionPhrases": [
        "DL-6号事件",
        "SL-9号事件",
        "DL-6"
      ]
    },
    "expected": {
      "reason": "keyword_with_verb",
      "keyword": "高日",
      "verb": "死んだ"
    }
  },
  {
    "name": "パターン3: KW単独（動詞なし）",
    "input": {
      "text": "高日について",
      "keywords": [
        "高日",
        "高日美佳",
        "Cindy Stone",
        "Cindy",
        "被害者",
        "山野",
        "山野星雄",
        "Frank Sahwit",
        "Sahwit",
        "犯人",
        "綾里千尋",
        "千尋",
        "Mia Fey",
        "Mia",
        "死んだ",
        "殺された",
        "小中",
        "小中大",
        "Redd White",
        "ブルーコープ",
        "Bluecorp",
        "綾里真宵",
        "真宵",
        "Maya Fey",
        "Maya",
        "逮捕",
        "容疑者",
        "口寄せ",
        "霊媒",
        "霊術",
        "channeling",
        "spirit channeling",
        "千尋を呼ぶ",
        "荷星",
        "荷星三郎",
        "Will Powers",
        "トノサマン",
        "被告",
        "衣袋",
        "衣袋武志",
        "Jack Hammer",
        "Hammer",
        "元俳優",
        "姫神",
        "姫神サクラ",
        "Dee Vasquez",
        "プロデューサー",
        "マフィア",
        "5年前",
        "事故",
        "スタジオ",
        "グローバルスタジオ",
        "Global Studios",
        "狩魔",
        "狩魔豪",
        "Manfred von Karma",
        "von Karma",
        "フォン・カルマ",
        "DL-6",
        "DL6",
        "15年前",
        "真相",
        "御剣信",
        "Gregory Edgeworth",
        "エレベーター",
        "生倉",
        "生倉雪夫",
        "Robert Hammond",
        "Hammond",
        "悪徳弁護士",
        "湖",
        "灰根",
        "灰根高太郎",
        "Yanni Yogi",
        "Yogi",
        "管理人",
        "怜侍の父",
        "弁護士",
        "射殺",
        "狩魔に殺された",
        "怜侍",
        "御剣",
        "トラウマ",
        "父を殺した",
        "地震",
        "銃",
        "多田敷",
        "多田敷道夫",
        "Bruce Goodman",
        "Goodman",
        "刑事",
        "宝月巴",
        "宝月",
        "Lana Skye",
        "Lana",
        "検事正",
        "巌徒",
        "巌徒海慈",
        "Damon Gant",
        "Gant",
        "署長",
        "警察署長",
        "SL-9",
        "SL9",
        "2年前",
        "証拠改ざん",
        "罪門直斗",
        "罪門",
        "Neil Marshall",
        "Neil",
        "青影",
        "青影丈",
        "Joe Darke",
        "Darke",
        "連続殺人犯",
        "宝月茜",
        "Ema Skye",
        "Ema",
        "科学捜査",
        "霊",
        "真宵から千尋",
        "Edgeworth",
        "協力",
        "改心",
        "変わった",
        "未解決事件",
        "御剣の過去",
        "因縁",
        "宿敵",
        "弟子",
        "助手",
        "パートナー",
        "綾里事務所"
      ],
      "descriptionPhrases": [
        "DL-6号事件",
        "SL-9号事件",
        "DL-6"
      ]
    },
    "expected": null
  },
  {
    "name": "パターン3: 動詞単独（KWなし）",
    "input": {
      "text": "誰かが死んだ",
      "keywords": [
        "高日",
        "高日美佳",
        "Cindy Stone",
        "Cindy",
        "被害者",
        "山野",
        "山野星雄",
        "Frank Sahwit",
        "Sahwit",
        "犯人",
        "綾里千尋",
        "千尋",
        "Mia Fey",
        "Mia",
        "死んだ",
        "殺された",
        "小中",
        "小中大",
        "Redd White",
        "ブルーコープ",
        "Bluecorp",
        "綾里真宵",
        "真宵",
        "Maya Fey",
        "Maya",
        "逮捕",
        "容疑者",
        "口寄せ",
        "霊媒",
        "霊術",
        "channeling",
        "spirit channeling",
        "千尋を呼ぶ",
        "荷星",
        "荷星三郎",
        "Will Powers",
        "トノサマン",
        "被告",
        "衣袋",
        "衣袋武志",
        "Jack Hammer",
        "Hammer",
        "元俳優",
        "姫神",
        "姫神サクラ",
        "Dee Vasquez",
        "プロデューサー",
        "マフィア",
        "5年前",
        "事故",
        "スタジオ",
        "グローバルスタジオ",
        "Global Studios",
        "狩魔",
        "狩魔豪",
        "Manfred von Karma",
        "von Karma",
        "フォン・カルマ",
        "DL-6",
        "DL6",
        "15年前",
        "真相",
        "御剣信",
        "Gregory Edgeworth",
        "エレベーター",
        "生倉",
        "生倉雪夫",
        "Robert Hammond",
        "Hammond",
        "悪徳弁護士",
        "湖",
        "灰根",
        "灰根高太郎",
        "Yanni Yogi",
        "Yogi",
        "管理人",
        "怜侍の父",
        "弁護士",
        "射殺",
        "狩魔に殺された",
        "怜侍",
        "御剣",
        "トラウマ",
        "父を殺した",
        "地震",
        "銃",
        "多田敷",
        "多田敷道夫",
        "Bruce Goodman",
        "Goodman",
        "刑事",
        "宝月巴",
        "宝月",
        "Lana Skye",
        "Lana",
        "検事正",
        "巌徒",
        "巌徒海慈",
        "Damon Gant",
        "Gant",
        "署長",
        "警察署長",
        "SL-9",
        "SL9",
        "2年前",
        "証拠改ざん",
        "罪門直斗",
        "罪門",
        "Neil Marshall",
        "Neil",
        "青影",
        "青影丈",
        "Joe Darke",
        "Darke",
        "連続殺人犯",
        "宝月茜",
        "Ema Skye",
        "Ema",
        "科学捜査",
        "霊",
        "真宵から千尋",
        "Edgeworth",
        "協力",
        "改心",
        "変わった",
        "未解決事件",
        "御剣の過去",
        "因縁",
        "宿敵",
        "弟子",
        "助手",
        "パートナー",
        "綾里事務所"
      ],
      "descriptionPhrases": [
        "DL-6号事件",
        "SL-9号事件",
        "DL-6"
      ]
    },
    "expected": {
      "reason": "keyword_with_verb",
      "keyword": "死んだ",
      "verb": "死んだ"
    }
  },
  {
    "name": "パターン3: 山野が犯人（KW+動詞）",
    "input": {
      "text": "山野が犯人だった",
      "keywords": [
        "高日",
        "高日美佳",
        "Cindy Stone",
        "Cindy",
        "被害者",
        "山野",
        "山野星雄",
        "Frank Sahwit",
        "Sahwit",
        "犯人",
        "綾里千尋",
        "千尋",
        "Mia Fey",
        "Mia",
        "死んだ",
        "殺された",
        "小中",
        "小中大",
        "Redd White",
        "ブルーコープ",
        "Bluecorp",
        "綾里真宵",
        "真宵",
        "Maya Fey",
        "Maya",
        "逮捕",
        "容疑者",
        "口寄せ",
        "霊媒",
        "霊術",
        "channeling",
        "spirit channeling",
        "千尋を呼ぶ",
        "荷星",
        "荷星三郎",
        "Will Powers",
        "トノサマン",
        "被告",
        "衣袋",
        "衣袋武志",
        "Jack Hammer",
        "Hammer",
        "元俳優",
        "姫神",
        "姫神サクラ",
        "Dee Vasquez",
        "プロデューサー",
        "マフィア",
        "5年前",
        "事故",
        "スタジオ",
        "グローバルスタジオ",
        "Global Studios",
        "狩魔",
        "狩魔豪",
        "Manfred von Karma",
        "von Karma",
        "フォン・カルマ",
        "DL-6",
        "DL6",
        "15年前",
        "真相",
        "御剣信",
        "Gregory Edgeworth",
        "エレベーター",
        "生倉",
        "生倉雪夫",
        "Robert Hammond",
        "Hammond",
        "悪徳弁護士",
        "湖",
        "灰根",
        "灰根高太郎",
        "Yanni Yogi",
        "Yogi",
        "管理人",
        "怜侍の父",
        "弁護士",
        "射殺",
        "狩魔に殺された",
        "怜侍",
        "御剣",
        "トラウマ",
        "父を殺した",
        "地震",
        "銃",
        "多田敷",
        "多田敷道夫",
        "Bruce Goodman",
        "Goodman",
        "刑事",
        "宝月巴",
        "宝月",
        "Lana Skye",
        "Lana",
        "検事正",
        "巌徒",
        "巌徒海慈",
        "Damon Gant",
        "Gant",
        "署長",
        "警察署長",
        "SL-9",
        "SL9",
        "2年前",
        "証拠改ざん",
        "罪門直斗",
        "罪門",
        "Neil Marshall",
        "Neil",
        "青影",
        "青影丈",
        "Joe Darke",
        "Darke",
        "連続殺人犯",
        "宝月茜",
        "Ema Skye",
        "Ema",
        "科学捜査",
        "霊",
        "真宵から千尋",
        "Edgeworth",
        "協力",
        "改心",
        "変わった",
        "未解決事件",
        "御剣の過去",
        "因縁",
        "宿敵",
        "弟子",
        "助手",
        "パートナー",
        "綾里事務所"
      ],
      "descriptionPhrases": [
        "DL-6号事件",
        "SL-9号事件",
        "DL-6"
      ]
    },
    "expected": null
  },
  {
    "name": "強度 strict: gameplay_hint も含む幅広いセット",
    "input": {
      "text": "これは何かのキーワードを含む？",
      "keywords": [
        "高日",
        "高日美佳",
        "Cindy Stone",
        "Cindy",
        "被害者",
        "山野",
        "山野星雄",
        "Frank Sahwit",
        "Sahwit",
        "犯人",
        "置き時計",
        "時計",
        "凶器",
        "clock",
        "綾里千尋",
        "千尋",
        "Mia Fey",
        "Mia",
        "死んだ",
        "殺された",
        "小中",
        "小中大",
        "Redd White",
        "ブルーコープ",
        "Bluecorp",
        "綾里真宵",
        "真宵",
        "Maya Fey",
        "Maya",
        "逮捕",
        "容疑者",
        "口寄せ",
        "霊媒",
        "霊術",
        "channeling",
        "spirit channeling",
        "千尋を呼ぶ",
        "荷星",
        "荷星三郎",
        "Will Powers",
        "トノサマン",
        "被告",
        "衣袋",
        "衣袋武志",
        "Jack Hammer",
        "Hammer",
        "元俳優",
        "姫神",
        "姫神サクラ",
        "Dee Vasquez",
        "プロデューサー",
        "マフィア",
        "5年前",
        "事故",
        "スタジオ",
        "グローバルスタジオ",
        "Global Studios",
        "狩魔",
        "狩魔豪",
        "Manfred von Karma",
        "von Karma",
        "フォン・カルマ",
        "DL-6",
        "DL6",
        "15年前",
        "真相",
        "御剣信",
        "Gregory Edgeworth",
        "エレベーター",
        "生倉",
        "生倉雪夫",
        "Robert Hammond",
        "Hammond",
        "悪徳弁護士",
        "湖",
        "灰根",
        "灰根高太郎",
        "Yanni Yogi",
        "Yogi",
        "管理人",
        "怜侍の父",
        "弁護士",
        "射殺",
        "狩魔に殺された",
        "怜侍",
        "御剣",
        "トラウマ",
        "父を殺した",
        "地震",
        "銃",
        "多田敷",
        "多田敷道夫",
        "Bruce Goodman",
        "Goodman",
        "刑事",
        "宝月巴",
        "宝月",
        "Lana Skye",
        "Lana",
        "検事正",
        "巌徒",
        "巌徒海慈",
        "Damon Gant",
        "Gant",
        "署長",
        "警察署長",
        "SL-9",
        "SL9",
        "2年前",
        "証拠改ざん",
        "罪門直斗",
        "罪門",
        "Neil Marshall",
        "Neil",
        "青影",
        "青影丈",
        "Joe Darke",
        "Darke",
        "連続殺人犯",
        "宝月茜",
        "Ema Skye",
        "Ema",
        "科学捜査",
        "霊",
        "真宵から千尋",
        "Edgeworth",
        "協力",
        "改心",
        "変わった",
        "未解決事件",
        "御剣の過去",
        "因縁",
        "宿敵",
        "弟子",
        "助手",
        "パートナー",
        "綾里事務所"
      ],
      "descriptionPhrases": [
        "DL-6号事件",
        "SL-9号事件",
        "DL-6"
      ]
    },
    "expected": null
  },
  {
    "name": "強度 standard: 標準セット",
    "input": {
      "text": "何でもないコメント",
      "keywords": [
        "高日",
        "高日美佳",
        "Cindy Stone",
        "Cindy",
        "被害者",
        "山野",
        "山野星雄",
        "Frank Sahwit",
        "Sahwit",
        "犯人",
        "綾里千尋",
        "千尋",
        "Mia Fey",
        "Mia",
        "死んだ",
        "殺された",
        "小中",
        "小中大",
        "Redd White",
        "ブルーコープ",
        "Bluecorp",
        "綾里真宵",
        "真宵",
        "Maya Fey",
        "Maya",
        "逮捕",
        "容疑者",
        "口寄せ",
        "霊媒",
        "霊術",
        "channeling",
        "spirit channeling",
        "千尋を呼ぶ",
        "荷星",
        "荷星三郎",
        "Will Powers",
        "トノサマン",
        "被告",
        "衣袋",
        "衣袋武志",
        "Jack Hammer",
        "Hammer",
        "元俳優",
        "姫神",
        "姫神サクラ",
        "Dee Vasquez",
        "プロデューサー",
        "マフィア",
        "5年前",
        "事故",
        "スタジオ",
        "グローバルスタジオ",
        "Global Studios",
        "狩魔",
        "狩魔豪",
        "Manfred von Karma",
        "von Karma",
        "フォン・カルマ",
        "DL-6",
        "DL6",
        "15年前",
        "真相",
        "御剣信",
        "Gregory Edgeworth",
        "エレベーター",
        "生倉",
        "生倉雪夫",
        "Robert Hammond",
        "Hammond",
        "悪徳弁護士",
        "湖",
        "灰根",
        "灰根高太郎",
        "Yanni Yogi",
        "Yogi",
        "管理人",
        "怜侍の父",
        "弁護士",
        "射殺",
        "狩魔に殺された",
        "怜侍",
        "御剣",
        "トラウマ",
        "父を殺した",
        "地震",
        "銃",
        "多田敷",
        "多田敷道夫",
        "Bruce Goodman",
        "Goodman",
        "刑事",
        "宝月巴",
        "宝月",
        "Lana Skye",
        "Lana",
        "検事正",
        "巌徒",
        "巌徒海慈",
        "Damon Gant",
        "Gant",
        "署長",
        "警察署長",
        "SL-9",
        "SL9",
        "2年前",
        "証拠改ざん",
        "罪門直斗",
        "罪門",
        "Neil Marshall",
        "Neil",
        "青影",
        "青影丈",
        "Joe Darke",
        "Darke",
        "連続殺人犯",
        "宝月茜",
        "Ema Skye",
        "Ema",
        "科学捜査",
        "霊",
        "真宵から千尋",
        "Edgeworth",
        "協力",
        "改心",
        "変わった",
        "未解決事件",
        "御剣の過去",
        "因縁",
        "宿敵",
        "弟子",
        "助手",
        "パートナー",
        "綾里事務所"
      ],
      "descriptionPhrases": [
        "DL-6号事件",
        "SL-9号事件",
        "DL-6"
      ]
    },
    "expected": null
  },
  {
    "name": "強度 lenient: direct_spoiler のみ",
    "input": {
      "text": "これは普通の文章",
      "keywords": [
        "高日",
        "高日美佳",
        "Cindy Stone",
        "Cindy",
        "被害者",
        "山野",
        "山野星雄",
        "Frank Sahwit",
        "Sahwit",
        "犯人",
        "綾里千尋",
        "千尋",
        "Mia Fey",
        "Mia",
        "死んだ",
        "殺された",
        "小中",
        "小中大",
        "Redd White",
        "ブルーコープ",
        "Bluecorp",
        "衣袋",
        "衣袋武志",
        "Jack Hammer",
        "Hammer",
        "トノサマン",
        "元俳優",
        "姫神",
        "姫神サクラ",
        "Dee Vasquez",
        "プロデューサー",
        "マフィア",
        "狩魔",
        "狩魔豪",
        "Manfred von Karma",
        "von Karma",
        "フォン・カルマ",
        "DL-6",
        "DL6",
        "15年前",
        "真相",
        "御剣信",
        "Gregory Edgeworth",
        "エレベーター",
        "生倉",
        "生倉雪夫",
        "Robert Hammond",
        "Hammond",
        "悪徳弁護士",
        "湖",
        "灰根",
        "灰根高太郎",
        "Yanni Yogi",
        "Yogi",
        "管理人",
        "怜侍の父",
        "弁護士",
        "射殺",
        "狩魔に殺された",
        "怜侍",
        "御剣",
        "トラウマ",
        "父を殺した",
        "地震",
        "銃",
        "多田敷",
        "多田敷道夫",
        "Bruce Goodman",
        "Goodman",
        "刑事",
        "宝月巴",
        "宝月",
        "Lana Skye",
        "Lana",
        "被告",
        "検事正",
        "巌徒",
        "巌徒海慈",
        "Damon Gant",
        "Gant",
        "署長",
        "警察署長",
        "SL-9",
        "SL9",
        "2年前",
        "証拠改ざん",
        "罪門直斗",
        "罪門",
        "Neil Marshall",
        "Neil",
        "青影",
        "青影丈",
        "Joe Darke",
        "Darke",
        "連続殺人犯",
        "宝月茜",
        "Ema Skye",
        "Ema",
        "科学捜査"
      ],
      "descriptionPhrases": [
        "DL-6号事件",
        "SL-9号事件",
        "DL-6"
      ]
    },
    "expected": null
  },
  {
    "name": "強度 lenient で direct_spoiler は依然block",
    "input": {
      "text": "高日が死んだ",
      "keywords": [
        "高日",
        "高日美佳",
        "Cindy Stone",
        "Cindy",
        "被害者",
        "山野",
        "山野星雄",
        "Frank Sahwit",
        "Sahwit",
        "犯人",
        "綾里千尋",
        "千尋",
        "Mia Fey",
        "Mia",
        "死んだ",
        "殺された",
        "小中",
        "小中大",
        "Redd White",
        "ブルーコープ",
        "Bluecorp",
        "衣袋",
        "衣袋武志",
        "Jack Hammer",
        "Hammer",
        "トノサマン",
        "元俳優",
        "姫神",
        "姫神サクラ",
        "Dee Vasquez",
        "プロデューサー",
        "マフィア",
        "狩魔",
        "狩魔豪",
        "Manfred von Karma",
        "von Karma",
        "フォン・カルマ",
        "DL-6",
        "DL6",
        "15年前",
        "真相",
        "御剣信",
        "Gregory Edgeworth",
        "エレベーター",
        "生倉",
        "生倉雪夫",
        "Robert Hammond",
        "Hammond",
        "悪徳弁護士",
        "湖",
        "灰根",
        "灰根高太郎",
        "Yanni Yogi",
        "Yogi",
        "管理人",
        "怜侍の父",
        "弁護士",
        "射殺",
        "狩魔に殺された",
        "怜侍",
        "御剣",
        "トラウマ",
        "父を殺した",
        "地震",
        "銃",
        "多田敷",
        "多田敷道夫",
        "Bruce Goodman",
        "Goodman",
        "刑事",
        "宝月巴",
        "宝月",
        "Lana Skye",
        "Lana",
        "被告",
        "検事正",
        "巌徒",
        "巌徒海慈",
        "Damon Gant",
        "Gant",
        "署長",
        "警察署長",
        "SL-9",
        "SL9",
        "2年前",
        "証拠改ざん",
        "罪門直斗",
        "罪門",
        "Neil Marshall",
        "Neil",
        "青影",
        "青影丈",
        "Joe Darke",
        "Darke",
        "連続殺人犯",
        "宝月茜",
        "Ema Skye",
        "Ema",
        "科学捜査"
      ],
      "descriptionPhrases": [
        "DL-6号事件",
        "SL-9号事件",
        "DL-6"
      ]
    },
    "expected": {
      "reason": "keyword_with_verb",
      "keyword": "高日",
      "verb": "死んだ"
    }
  },
  {
    "name": "進行 ch1: KW依然block（DL-6 は ch4 解禁前）",
    "input": {
      "text": "DL-6号事件",
      "keywords": [
        "高日",
        "高日美佳",
        "Cindy Stone",
        "Cindy",
        "被害者",
        "山野",
        "山野星雄",
        "Frank Sahwit",
        "Sahwit",
        "犯人",
        "綾里千尋",
        "千尋",
        "Mia Fey",
        "Mia",
        "死んだ",
        "殺された",
        "小中",
        "小中大",
        "Redd White",
        "ブルーコープ",
        "Bluecorp",
        "綾里真宵",
        "真宵",
        "Maya Fey",
        "Maya",
        "逮捕",
        "容疑者",
        "口寄せ",
        "霊媒",
        "霊術",
        "channeling",
        "spirit channeling",
        "千尋を呼ぶ",
        "荷星",
        "荷星三郎",
        "Will Powers",
        "トノサマン",
        "被告",
        "衣袋",
        "衣袋武志",
        "Jack Hammer",
        "Hammer",
        "元俳優",
        "姫神",
        "姫神サクラ",
        "Dee Vasquez",
        "プロデューサー",
        "マフィア",
        "5年前",
        "事故",
        "スタジオ",
        "グローバルスタジオ",
        "Global Studios",
        "狩魔",
        "狩魔豪",
        "Manfred von Karma",
        "von Karma",
        "フォン・カルマ",
        "DL-6",
        "DL6",
        "15年前",
        "真相",
        "御剣信",
        "Gregory Edgeworth",
        "エレベーター",
        "生倉",
        "生倉雪夫",
        "Robert Hammond",
        "Hammond",
        "悪徳弁護士",
        "湖",
        "灰根",
        "灰根高太郎",
        "Yanni Yogi",
        "Yogi",
        "管理人",
        "怜侍の父",
        "弁護士",
        "射殺",
        "狩魔に殺された",
        "怜侍",
        "御剣",
        "トラウマ",
        "父を殺した",
        "地震",
        "銃",
        "多田敷",
        "多田敷道夫",
        "Bruce Goodman",
        "Goodman",
        "刑事",
        "宝月巴",
        "宝月",
        "Lana Skye",
        "Lana",
        "検事正",
        "巌徒",
        "巌徒海慈",
        "Damon Gant",
        "Gant",
        "署長",
        "警察署長",
        "SL-9",
        "SL9",
        "2年前",
        "証拠改ざん",
        "罪門直斗",
        "罪門",
        "Neil Marshall",
        "Neil",
        "青影",
        "青影丈",
        "Joe Darke",
        "Darke",
        "連続殺人犯",
        "宝月茜",
        "Ema Skye",
        "Ema",
        "科学捜査",
        "霊",
        "真宵から千尋",
        "Edgeworth",
        "協力",
        "改心",
        "変わった",
        "未解決事件",
        "御剣の過去",
        "因縁",
        "宿敵",
        "弟子",
        "助手",
        "パートナー",
        "綾里事務所"
      ],
      "descriptionPhrases": [
        "DL-6号事件",
        "SL-9号事件",
        "DL-6"
      ]
    },
    "expected": {
      "reason": "description_phrase",
      "phrase": "DL-6号事件"
    }
  },
  {
    "name": "進行 ch3: 中盤、KW縮小",
    "input": {
      "text": "何でもないコメント",
      "keywords": [
        "荷星",
        "荷星三郎",
        "Will Powers",
        "トノサマン",
        "被告",
        "衣袋",
        "衣袋武志",
        "Jack Hammer",
        "Hammer",
        "被害者",
        "元俳優",
        "姫神",
        "姫神サクラ",
        "Dee Vasquez",
        "プロデューサー",
        "マフィア",
        "犯人",
        "5年前",
        "事故",
        "スタジオ",
        "グローバルスタジオ",
        "Global Studios",
        "狩魔",
        "狩魔豪",
        "Manfred von Karma",
        "von Karma",
        "フォン・カルマ",
        "DL-6",
        "DL6",
        "15年前",
        "真相",
        "御剣信",
        "Gregory Edgeworth",
        "エレベーター",
        "生倉",
        "生倉雪夫",
        "Robert Hammond",
        "Hammond",
        "悪徳弁護士",
        "湖",
        "灰根",
        "灰根高太郎",
        "Yanni Yogi",
        "Yogi",
        "管理人",
        "怜侍の父",
        "弁護士",
        "射殺",
        "狩魔に殺された",
        "怜侍",
        "御剣",
        "トラウマ",
        "父を殺した",
        "地震",
        "銃",
        "多田敷",
        "多田敷道夫",
        "Bruce Goodman",
        "Goodman",
        "刑事",
        "宝月巴",
        "宝月",
        "Lana Skye",
        "Lana",
        "検事正",
        "巌徒",
        "巌徒海慈",
        "Damon Gant",
        "Gant",
        "署長",
        "警察署長",
        "SL-9",
        "SL9",
        "2年前",
        "証拠改ざん",
        "罪門直斗",
        "罪門",
        "Neil Marshall",
        "Neil",
        "殺された",
        "青影",
        "青影丈",
        "Joe Darke",
        "Darke",
        "連続殺人犯",
        "宝月茜",
        "Ema Skye",
        "Ema",
        "科学捜査",
        "千尋",
        "口寄せ",
        "Mia",
        "霊",
        "真宵から千尋",
        "spirit channeling",
        "Edgeworth",
        "協力",
        "改心",
        "変わった",
        "未解決事件",
        "御剣の過去",
        "因縁",
        "宿敵",
        "弟子",
        "真宵",
        "Maya",
        "助手",
        "パートナー",
        "綾里事務所"
      ],
      "descriptionPhrases": [
        "DL-6号事件",
        "SL-9号事件",
        "DL-6"
      ]
    },
    "expected": null
  },
  {
    "name": "進行 ch5: 終盤、最大限解禁",
    "input": {
      "text": "何でもないコメント",
      "keywords": [
        "多田敷",
        "多田敷道夫",
        "Bruce Goodman",
        "Goodman",
        "被害者",
        "刑事",
        "宝月巴",
        "宝月",
        "Lana Skye",
        "Lana",
        "被告",
        "検事正",
        "巌徒",
        "巌徒海慈",
        "Damon Gant",
        "Gant",
        "署長",
        "警察署長",
        "犯人",
        "SL-9",
        "SL9",
        "2年前",
        "真相",
        "証拠改ざん",
        "罪門直斗",
        "罪門",
        "Neil Marshall",
        "Neil",
        "殺された",
        "青影",
        "青影丈",
        "Joe Darke",
        "Darke",
        "連続殺人犯",
        "宝月茜",
        "Ema Skye",
        "Ema",
        "科学捜査",
        "千尋",
        "口寄せ",
        "Mia",
        "霊",
        "真宵から千尋",
        "spirit channeling",
        "御剣",
        "怜侍",
        "Edgeworth",
        "協力",
        "改心",
        "変わった",
        "DL-6",
        "DL6",
        "15年前",
        "未解決事件",
        "御剣の過去",
        "狩魔",
        "狩魔豪",
        "von Karma",
        "因縁",
        "宿敵",
        "弟子",
        "真宵",
        "Maya",
        "助手",
        "パートナー",
        "綾里事務所"
      ],
      "descriptionPhrases": [
        "DL-6号事件",
        "SL-9号事件",
        "DL-6"
      ]
    },
    "expected": null
  },
  {
    "name": "マッチなし: 草",
    "input": {
      "text": "草",
      "keywords": [
        "高日",
        "高日美佳",
        "Cindy Stone",
        "Cindy",
        "被害者",
        "山野",
        "山野星雄",
        "Frank Sahwit",
        "Sahwit",
        "犯人",
        "綾里千尋",
        "千尋",
        "Mia Fey",
        "Mia",
        "死んだ",
        "殺された",
        "小中",
        "小中大",
        "Redd White",
        "ブルーコープ",
        "Bluecorp",
        "綾里真宵",
        "真宵",
        "Maya Fey",
        "Maya",
        "逮捕",
        "容疑者",
        "口寄せ",
        "霊媒",
        "霊術",
        "channeling",
        "spirit channeling",
        "千尋を呼ぶ",
        "荷星",
        "荷星三郎",
        "Will Powers",
        "トノサマン",
        "被告",
        "衣袋",
        "衣袋武志",
        "Jack Hammer",
        "Hammer",
        "元俳優",
        "姫神",
        "姫神サクラ",
        "Dee Vasquez",
        "プロデューサー",
        "マフィア",
        "5年前",
        "事故",
        "スタジオ",
        "グローバルスタジオ",
        "Global Studios",
        "狩魔",
        "狩魔豪",
        "Manfred von Karma",
        "von Karma",
        "フォン・カルマ",
        "DL-6",
        "DL6",
        "15年前",
        "真相",
        "御剣信",
        "Gregory Edgeworth",
        "エレベーター",
        "生倉",
        "生倉雪夫",
        "Robert Hammond",
        "Hammond",
        "悪徳弁護士",
        "湖",
        "灰根",
        "灰根高太郎",
        "Yanni Yogi",
        "Yogi",
        "管理人",
        "怜侍の父",
        "弁護士",
        "射殺",
        "狩魔に殺された",
        "怜侍",
        "御剣",
        "トラウマ",
        "父を殺した",
        "地震",
        "銃",
        "多田敷",
        "多田敷道夫",
        "Bruce Goodman",
        "Goodman",
        "刑事",
        "宝月巴",
        "宝月",
        "Lana Skye",
        "Lana",
        "検事正",
        "巌徒",
        "巌徒海慈",
        "Damon Gant",
        "Gant",
        "署長",
        "警察署長",
        "SL-9",
        "SL9",
        "2年前",
        "証拠改ざん",
        "罪門直斗",
        "罪門",
        "Neil Marshall",
        "Neil",
        "青影",
        "青影丈",
        "Joe Darke",
        "Darke",
        "連続殺人犯",
        "宝月茜",
        "Ema Skye",
        "Ema",
        "科学捜査",
        "霊",
        "真宵から千尋",
        "Edgeworth",
        "協力",
        "改心",
        "変わった",
        "未解決事件",
        "御剣の過去",
        "因縁",
        "宿敵",
        "弟子",
        "助手",
        "パートナー",
        "綾里事務所"
      ],
      "descriptionPhrases": [
        "DL-6号事件",
        "SL-9号事件",
        "DL-6"
      ]
    },
    "expected": null
  },
  {
    "name": "マッチなし: www",
    "input": {
      "text": "www",
      "keywords": [
        "高日",
        "高日美佳",
        "Cindy Stone",
        "Cindy",
        "被害者",
        "山野",
        "山野星雄",
        "Frank Sahwit",
        "Sahwit",
        "犯人",
        "綾里千尋",
        "千尋",
        "Mia Fey",
        "Mia",
        "死んだ",
        "殺された",
        "小中",
        "小中大",
        "Redd White",
        "ブルーコープ",
        "Bluecorp",
        "綾里真宵",
        "真宵",
        "Maya Fey",
        "Maya",
        "逮捕",
        "容疑者",
        "口寄せ",
        "霊媒",
        "霊術",
        "channeling",
        "spirit channeling",
        "千尋を呼ぶ",
        "荷星",
        "荷星三郎",
        "Will Powers",
        "トノサマン",
        "被告",
        "衣袋",
        "衣袋武志",
        "Jack Hammer",
        "Hammer",
        "元俳優",
        "姫神",
        "姫神サクラ",
        "Dee Vasquez",
        "プロデューサー",
        "マフィア",
        "5年前",
        "事故",
        "スタジオ",
        "グローバルスタジオ",
        "Global Studios",
        "狩魔",
        "狩魔豪",
        "Manfred von Karma",
        "von Karma",
        "フォン・カルマ",
        "DL-6",
        "DL6",
        "15年前",
        "真相",
        "御剣信",
        "Gregory Edgeworth",
        "エレベーター",
        "生倉",
        "生倉雪夫",
        "Robert Hammond",
        "Hammond",
        "悪徳弁護士",
        "湖",
        "灰根",
        "灰根高太郎",
        "Yanni Yogi",
        "Yogi",
        "管理人",
        "怜侍の父",
        "弁護士",
        "射殺",
        "狩魔に殺された",
        "怜侍",
        "御剣",
        "トラウマ",
        "父を殺した",
        "地震",
        "銃",
        "多田敷",
        "多田敷道夫",
        "Bruce Goodman",
        "Goodman",
        "刑事",
        "宝月巴",
        "宝月",
        "Lana Skye",
        "Lana",
        "検事正",
        "巌徒",
        "巌徒海慈",
        "Damon Gant",
        "Gant",
        "署長",
        "警察署長",
        "SL-9",
        "SL9",
        "2年前",
        "証拠改ざん",
        "罪門直斗",
        "罪門",
        "Neil Marshall",
        "Neil",
        "青影",
        "青影丈",
        "Joe Darke",
        "Darke",
        "連続殺人犯",
        "宝月茜",
        "Ema Skye",
        "Ema",
        "科学捜査",
        "霊",
        "真宵から千尋",
        "Edgeworth",
        "協力",
        "改心",
        "変わった",
        "未解決事件",
        "御剣の過去",
        "因縁",
        "宿敵",
        "弟子",
        "助手",
        "パートナー",
        "綾里事務所"
      ],
      "descriptionPhrases": [
        "DL-6号事件",
        "SL-9号事件",
        "DL-6"
      ]
    },
    "expected": null
  },
  {
    "name": "カナ正規化: 全角英数のフレーズ「ＤＬ－６号事件」",
    "input": {
      "text": "ＤＬ－６号事件って気になる",
      "keywords": [
        "高日",
        "高日美佳",
        "Cindy Stone",
        "Cindy",
        "被害者",
        "山野",
        "山野星雄",
        "Frank Sahwit",
        "Sahwit",
        "犯人",
        "綾里千尋",
        "千尋",
        "Mia Fey",
        "Mia",
        "死んだ",
        "殺された",
        "小中",
        "小中大",
        "Redd White",
        "ブルーコープ",
        "Bluecorp",
        "綾里真宵",
        "真宵",
        "Maya Fey",
        "Maya",
        "逮捕",
        "容疑者",
        "口寄せ",
        "霊媒",
        "霊術",
        "channeling",
        "spirit channeling",
        "千尋を呼ぶ",
        "荷星",
        "荷星三郎",
        "Will Powers",
        "トノサマン",
        "被告",
        "衣袋",
        "衣袋武志",
        "Jack Hammer",
        "Hammer",
        "元俳優",
        "姫神",
        "姫神サクラ",
        "Dee Vasquez",
        "プロデューサー",
        "マフィア",
        "5年前",
        "事故",
        "スタジオ",
        "グローバルスタジオ",
        "Global Studios",
        "狩魔",
        "狩魔豪",
        "Manfred von Karma",
        "von Karma",
        "フォン・カルマ",
        "DL-6",
        "DL6",
        "15年前",
        "真相",
        "御剣信",
        "Gregory Edgeworth",
        "エレベーター",
        "生倉",
        "生倉雪夫",
        "Robert Hammond",
        "Hammond",
        "悪徳弁護士",
        "湖",
        "灰根",
        "灰根高太郎",
        "Yanni Yogi",
        "Yogi",
        "管理人",
        "怜侍の父",
        "弁護士",
        "射殺",
        "狩魔に殺された",
        "怜侍",
        "御剣",
        "トラウマ",
        "父を殺した",
        "地震",
        "銃",
        "多田敷",
        "多田敷道夫",
        "Bruce Goodman",
        "Goodman",
        "刑事",
        "宝月巴",
        "宝月",
        "Lana Skye",
        "Lana",
        "検事正",
        "巌徒",
        "巌徒海慈",
        "Damon Gant",
        "Gant",
        "署長",
        "警察署長",
        "SL-9",
        "SL9",
        "2年前",
        "証拠改ざん",
        "罪門直斗",
        "罪門",
        "Neil Marshall",
        "Neil",
        "青影",
        "青影丈",
        "Joe Darke",
        "Darke",
        "連続殺人犯",
        "宝月茜",
        "Ema Skye",
        "Ema",
        "科学捜査",
        "霊",
        "真宵から千尋",
        "Edgeworth",
        "協力",
        "改心",
        "変わった",
        "未解決事件",
        "御剣の過去",
        "因縁",
        "宿敵",
        "弟子",
        "助手",
        "パートナー",
        "綾里事務所"
      ],
      "descriptionPhrases": [
        "DL-6号事件",
        "SL-9号事件",
        "DL-6"
      ]
    },
    "expected": {
      "reason": "description_phrase",
      "phrase": "DL-6号事件"
    }
  },
  {
    "name": "複合: カナ正規化 + 知識ベース設計（やまのは1話既知のため非ネタバレ）",
    "comment": "現状 normalizeKana は漢字→ひらがな変換を行わないため expected: null。ただしこのケースは仮にカナ正規化が将来改善されても expected: null が正解。なぜなら「やまの」は逆転裁判1の1話冒頭で犯人として公開されるキャラクターであり、知識ベース側で unlocked_after_chapter 等によりブロック対象から外れるべきだから。本フィクスチャはカナ正規化と知識ベース設計の両方が絡む複合ケースであり、Phase 3 以降でカナ正規化を拡張する際の回帰テストとしても意味を持つ。",
    "input": {
      "text": "やまのが犯人だった",
      "keywords": [
        "高日",
        "高日美佳",
        "Cindy Stone",
        "Cindy",
        "被害者",
        "山野",
        "山野星雄",
        "Frank Sahwit",
        "Sahwit",
        "犯人",
        "綾里千尋",
        "千尋",
        "Mia Fey",
        "Mia",
        "死んだ",
        "殺された",
        "小中",
        "小中大",
        "Redd White",
        "ブルーコープ",
        "Bluecorp",
        "綾里真宵",
        "真宵",
        "Maya Fey",
        "Maya",
        "逮捕",
        "容疑者",
        "口寄せ",
        "霊媒",
        "霊術",
        "channeling",
        "spirit channeling",
        "千尋を呼ぶ",
        "荷星",
        "荷星三郎",
        "Will Powers",
        "トノサマン",
        "被告",
        "衣袋",
        "衣袋武志",
        "Jack Hammer",
        "Hammer",
        "元俳優",
        "姫神",
        "姫神サクラ",
        "Dee Vasquez",
        "プロデューサー",
        "マフィア",
        "5年前",
        "事故",
        "スタジオ",
        "グローバルスタジオ",
        "Global Studios",
        "狩魔",
        "狩魔豪",
        "Manfred von Karma",
        "von Karma",
        "フォン・カルマ",
        "DL-6",
        "DL6",
        "15年前",
        "真相",
        "御剣信",
        "Gregory Edgeworth",
        "エレベーター",
        "生倉",
        "生倉雪夫",
        "Robert Hammond",
        "Hammond",
        "悪徳弁護士",
        "湖",
        "灰根",
        "灰根高太郎",
        "Yanni Yogi",
        "Yogi",
        "管理人",
        "怜侍の父",
        "弁護士",
        "射殺",
        "狩魔に殺された",
        "怜侍",
        "御剣",
        "トラウマ",
        "父を殺した",
        "地震",
        "銃",
        "多田敷",
        "多田敷道夫",
        "Bruce Goodman",
        "Goodman",
        "刑事",
        "宝月巴",
        "宝月",
        "Lana Skye",
        "Lana",
        "検事正",
        "巌徒",
        "巌徒海慈",
        "Damon Gant",
        "Gant",
        "署長",
        "警察署長",
        "SL-9",
        "SL9",
        "2年前",
        "証拠改ざん",
        "罪門直斗",
        "罪門",
        "Neil Marshall",
        "Neil",
        "青影",
        "青影丈",
        "Joe Darke",
        "Darke",
        "連続殺人犯",
        "宝月茜",
        "Ema Skye",
        "Ema",
        "科学捜査",
        "霊",
        "真宵から千尋",
        "Edgeworth",
        "協力",
        "改心",
        "変わった",
        "未解決事件",
        "御剣の過去",
        "因縁",
        "宿敵",
        "弟子",
        "助手",
        "パートナー",
        "綾里事務所"
      ],
      "descriptionPhrases": [
        "DL-6号事件",
        "SL-9号事件",
        "DL-6"
      ]
    },
    "expected": null
  }
];

// ─── B. matchesCustomNGWord ──────────────────────────────────────────
export interface MatchesCustomNGWordFixture {
  name: string;
  input: { text: string; words: { id: string; word: string; enabled: boolean }[] };
  expected: string | null;
}

export const MATCHES_CUSTOM_NG_WORD_FIXTURES: MatchesCustomNGWordFixture[] = [
  {
    "name": "enabled マッチ",
    "input": {
      "text": "これは秘密のワードです",
      "words": [
        {
          "id": "1",
          "word": "秘密",
          "enabled": true
        }
      ]
    },
    "expected": "秘密"
  },
  {
    "name": "enabled マッチ（カナ揺れ）",
    "input": {
      "text": "ねたバレ全開",
      "words": [
        {
          "id": "1",
          "word": "ネタバレ",
          "enabled": true
        }
      ]
    },
    "expected": "ネタバレ"
  },
  {
    "name": "disabled は無視",
    "input": {
      "text": "これは秘密のワードです",
      "words": [
        {
          "id": "1",
          "word": "秘密",
          "enabled": false
        }
      ]
    },
    "expected": null
  },
  {
    "name": "全 disabled",
    "input": {
      "text": "何でも",
      "words": [
        {
          "id": "1",
          "word": "何でも",
          "enabled": false
        },
        {
          "id": "2",
          "word": "てきとう",
          "enabled": false
        }
      ]
    },
    "expected": null
  },
  {
    "name": "空リスト",
    "input": {
      "text": "何でも",
      "words": []
    },
    "expected": null
  },
  {
    "name": "部分一致 enabled",
    "input": {
      "text": "スーパースペシャル展開",
      "words": [
        {
          "id": "1",
          "word": "スペシャル",
          "enabled": true
        }
      ]
    },
    "expected": "スペシャル"
  }
];

// ─── C. matchesGenreTemplate ─────────────────────────────────────────
export interface MatchesGenreTemplateFixture {
  name: string;
  input: { text: string; templateIds: string[] };
  expected: string | null;
}

export const MATCHES_GENRE_TEMPLATE_FIXTURES: MatchesGenreTemplateFixture[] = [
  {
    "name": "RPG context_phrase「ラスボスは」",
    "input": {
      "text": "ラスボスは○○だよ",
      "templateIds": [
        "rpg"
      ]
    },
    "expected": "ラスボスは"
  },
  {
    "name": "RPG context_phrase「真の黒幕は」",
    "input": {
      "text": "やっぱり真の黒幕は彼だった",
      "templateIds": [
        "rpg"
      ]
    },
    "expected": "真の黒幕は"
  },
  {
    "name": "RPG keyword「ラスボス」+ 動詞「死んだ」",
    "input": {
      "text": "ラスボスは死んだ",
      "templateIds": [
        "rpg"
      ]
    },
    "expected": "ラスボスは"
  },
  {
    "name": "Mystery context_phrase「犯人は」",
    "input": {
      "text": "犯人は身近な人物",
      "templateIds": [
        "mystery"
      ]
    },
    "expected": "犯人は"
  },
  {
    "name": "Mystery keyword単独 → null",
    "input": {
      "text": "犯人いるよね",
      "templateIds": [
        "mystery"
      ]
    },
    "expected": null
  },
  {
    "name": "複数テンプレート（RPG+Mystery）",
    "input": {
      "text": "ラスボスは犯人だった",
      "templateIds": [
        "rpg",
        "mystery"
      ]
    },
    "expected": "ラスボスは"
  },
  {
    "name": "空テンプレート → null",
    "input": {
      "text": "ラスボスは○○",
      "templateIds": []
    },
    "expected": null
  },
  {
    "name": "該当なし: 一般的なテキスト",
    "input": {
      "text": "こんにちは皆さん",
      "templateIds": [
        "rpg",
        "mystery"
      ]
    },
    "expected": null
  },
  {
    "name": "action-horror context_phrase",
    "input": {
      "text": "主人公は実は死んでた",
      "templateIds": [
        "action-horror"
      ]
    },
    "expected": null
  },
  {
    "name": "story-general context_phrase",
    "input": {
      "text": "黒幕は副官だった",
      "templateIds": [
        "story-general"
      ]
    },
    "expected": null
  }
];

// ─── D. matchesGameplayHintForStage2 ─────────────────────────────────
export interface MatchesGameplayHintFixture {
  name: string;
  input: { text: string; templateIds: string[] };
  expected: string | null;
}

export const MATCHES_GAMEPLAY_HINT_FIXTURES: MatchesGameplayHintFixture[] = [
  {
    "name": "gameplay-hints stage2_phrases にマッチ",
    "input": {
      "text": "このボス、弱点は炎だよ",
      "templateIds": [
        "gameplay-hints"
      ]
    },
    "expected": null
  },
  {
    "name": "stage2_phrases なしテンプレート（RPG）",
    "input": {
      "text": "何でも",
      "templateIds": [
        "rpg"
      ]
    },
    "expected": null
  },
  {
    "name": "空テンプレート",
    "input": {
      "text": "何でも",
      "templateIds": []
    },
    "expected": null
  },
  {
    "name": "部分マッチ",
    "input": {
      "text": "なるほど、これ攻略法は左から行くといい",
      "templateIds": [
        "gameplay-hints"
      ]
    },
    "expected": null
  },
  {
    "name": "該当なし",
    "input": {
      "text": "こんにちは",
      "templateIds": [
        "gameplay-hints"
      ]
    },
    "expected": null
  }
];

// ─── E. matchesGenreKeywordForStage2 ─────────────────────────────────
export interface MatchesGenreKeywordFixture {
  name: string;
  input: { text: string; templateIds: string[] };
  expected: string | null;
}

export const MATCHES_GENRE_KEYWORD_FIXTURES: MatchesGenreKeywordFixture[] = [
  {
    "name": "RPG keyword単独マッチ",
    "input": {
      "text": "ラスボスについて話そう",
      "templateIds": [
        "rpg"
      ]
    },
    "expected": "ラスボス"
  },
  {
    "name": "Mystery keyword単独マッチ",
    "input": {
      "text": "犯人気になる",
      "templateIds": [
        "mystery"
      ]
    },
    "expected": "犯人"
  },
  {
    "name": "該当なし",
    "input": {
      "text": "こんにちは",
      "templateIds": [
        "rpg"
      ]
    },
    "expected": null
  },
  {
    "name": "空テンプレート",
    "input": {
      "text": "ラスボス",
      "templateIds": []
    },
    "expected": null
  },
  {
    "name": "複数テンプレート",
    "input": {
      "text": "裏ボス強い",
      "templateIds": [
        "rpg",
        "mystery"
      ]
    },
    "expected": "裏ボス"
  }
];

// ─── F. matchesKeywordForStage2 ──────────────────────────────────────
export interface MatchesKeywordForStage2Fixture {
  name: string;
  input: { text: string; keywords: string[] };
  expected: string | null;
}

export const MATCHES_KEYWORD_FOR_STAGE2_FIXTURES: MatchesKeywordForStage2Fixture[] = [
  {
    "name": "KW単独マッチ",
    "input": {
      "text": "高日についてどう思う",
      "keywords": [
        "高日",
        "高日美佳",
        "Cindy Stone",
        "Cindy",
        "被害者",
        "山野",
        "山野星雄",
        "Frank Sahwit",
        "Sahwit",
        "犯人",
        "綾里千尋",
        "千尋",
        "Mia Fey",
        "Mia",
        "死んだ",
        "殺された",
        "小中",
        "小中大",
        "Redd White",
        "ブルーコープ",
        "Bluecorp",
        "綾里真宵",
        "真宵",
        "Maya Fey",
        "Maya",
        "逮捕",
        "容疑者",
        "口寄せ",
        "霊媒",
        "霊術",
        "channeling",
        "spirit channeling",
        "千尋を呼ぶ",
        "荷星",
        "荷星三郎",
        "Will Powers",
        "トノサマン",
        "被告",
        "衣袋",
        "衣袋武志",
        "Jack Hammer",
        "Hammer",
        "元俳優",
        "姫神",
        "姫神サクラ",
        "Dee Vasquez",
        "プロデューサー",
        "マフィア",
        "5年前",
        "事故",
        "スタジオ",
        "グローバルスタジオ",
        "Global Studios",
        "狩魔",
        "狩魔豪",
        "Manfred von Karma",
        "von Karma",
        "フォン・カルマ",
        "DL-6",
        "DL6",
        "15年前",
        "真相",
        "御剣信",
        "Gregory Edgeworth",
        "エレベーター",
        "生倉",
        "生倉雪夫",
        "Robert Hammond",
        "Hammond",
        "悪徳弁護士",
        "湖",
        "灰根",
        "灰根高太郎",
        "Yanni Yogi",
        "Yogi",
        "管理人",
        "怜侍の父",
        "弁護士",
        "射殺",
        "狩魔に殺された",
        "怜侍",
        "御剣",
        "トラウマ",
        "父を殺した",
        "地震",
        "銃",
        "多田敷",
        "多田敷道夫",
        "Bruce Goodman",
        "Goodman",
        "刑事",
        "宝月巴",
        "宝月",
        "Lana Skye",
        "Lana",
        "検事正",
        "巌徒",
        "巌徒海慈",
        "Damon Gant",
        "Gant",
        "署長",
        "警察署長",
        "SL-9",
        "SL9",
        "2年前",
        "証拠改ざん",
        "罪門直斗",
        "罪門",
        "Neil Marshall",
        "Neil",
        "青影",
        "青影丈",
        "Joe Darke",
        "Darke",
        "連続殺人犯",
        "宝月茜",
        "Ema Skye",
        "Ema",
        "科学捜査",
        "霊",
        "真宵から千尋",
        "Edgeworth",
        "協力",
        "改心",
        "変わった",
        "未解決事件",
        "御剣の過去",
        "因縁",
        "宿敵",
        "弟子",
        "助手",
        "パートナー",
        "綾里事務所"
      ]
    },
    "expected": "高日"
  },
  {
    "name": "部分一致",
    "input": {
      "text": "山野星雄は",
      "keywords": [
        "高日",
        "高日美佳",
        "Cindy Stone",
        "Cindy",
        "被害者",
        "山野",
        "山野星雄",
        "Frank Sahwit",
        "Sahwit",
        "犯人",
        "綾里千尋",
        "千尋",
        "Mia Fey",
        "Mia",
        "死んだ",
        "殺された",
        "小中",
        "小中大",
        "Redd White",
        "ブルーコープ",
        "Bluecorp",
        "綾里真宵",
        "真宵",
        "Maya Fey",
        "Maya",
        "逮捕",
        "容疑者",
        "口寄せ",
        "霊媒",
        "霊術",
        "channeling",
        "spirit channeling",
        "千尋を呼ぶ",
        "荷星",
        "荷星三郎",
        "Will Powers",
        "トノサマン",
        "被告",
        "衣袋",
        "衣袋武志",
        "Jack Hammer",
        "Hammer",
        "元俳優",
        "姫神",
        "姫神サクラ",
        "Dee Vasquez",
        "プロデューサー",
        "マフィア",
        "5年前",
        "事故",
        "スタジオ",
        "グローバルスタジオ",
        "Global Studios",
        "狩魔",
        "狩魔豪",
        "Manfred von Karma",
        "von Karma",
        "フォン・カルマ",
        "DL-6",
        "DL6",
        "15年前",
        "真相",
        "御剣信",
        "Gregory Edgeworth",
        "エレベーター",
        "生倉",
        "生倉雪夫",
        "Robert Hammond",
        "Hammond",
        "悪徳弁護士",
        "湖",
        "灰根",
        "灰根高太郎",
        "Yanni Yogi",
        "Yogi",
        "管理人",
        "怜侍の父",
        "弁護士",
        "射殺",
        "狩魔に殺された",
        "怜侍",
        "御剣",
        "トラウマ",
        "父を殺した",
        "地震",
        "銃",
        "多田敷",
        "多田敷道夫",
        "Bruce Goodman",
        "Goodman",
        "刑事",
        "宝月巴",
        "宝月",
        "Lana Skye",
        "Lana",
        "検事正",
        "巌徒",
        "巌徒海慈",
        "Damon Gant",
        "Gant",
        "署長",
        "警察署長",
        "SL-9",
        "SL9",
        "2年前",
        "証拠改ざん",
        "罪門直斗",
        "罪門",
        "Neil Marshall",
        "Neil",
        "青影",
        "青影丈",
        "Joe Darke",
        "Darke",
        "連続殺人犯",
        "宝月茜",
        "Ema Skye",
        "Ema",
        "科学捜査",
        "霊",
        "真宵から千尋",
        "Edgeworth",
        "協力",
        "改心",
        "変わった",
        "未解決事件",
        "御剣の過去",
        "因縁",
        "宿敵",
        "弟子",
        "助手",
        "パートナー",
        "綾里事務所"
      ]
    },
    "expected": "山野"
  },
  {
    "name": "空セット → null",
    "input": {
      "text": "高日",
      "keywords": []
    },
    "expected": null
  },
  {
    "name": "該当しないテキスト",
    "input": {
      "text": "こんにちは皆さん",
      "keywords": [
        "高日",
        "高日美佳",
        "Cindy Stone",
        "Cindy",
        "被害者",
        "山野",
        "山野星雄",
        "Frank Sahwit",
        "Sahwit",
        "犯人",
        "綾里千尋",
        "千尋",
        "Mia Fey",
        "Mia",
        "死んだ",
        "殺された",
        "小中",
        "小中大",
        "Redd White",
        "ブルーコープ",
        "Bluecorp",
        "綾里真宵",
        "真宵",
        "Maya Fey",
        "Maya",
        "逮捕",
        "容疑者",
        "口寄せ",
        "霊媒",
        "霊術",
        "channeling",
        "spirit channeling",
        "千尋を呼ぶ",
        "荷星",
        "荷星三郎",
        "Will Powers",
        "トノサマン",
        "被告",
        "衣袋",
        "衣袋武志",
        "Jack Hammer",
        "Hammer",
        "元俳優",
        "姫神",
        "姫神サクラ",
        "Dee Vasquez",
        "プロデューサー",
        "マフィア",
        "5年前",
        "事故",
        "スタジオ",
        "グローバルスタジオ",
        "Global Studios",
        "狩魔",
        "狩魔豪",
        "Manfred von Karma",
        "von Karma",
        "フォン・カルマ",
        "DL-6",
        "DL6",
        "15年前",
        "真相",
        "御剣信",
        "Gregory Edgeworth",
        "エレベーター",
        "生倉",
        "生倉雪夫",
        "Robert Hammond",
        "Hammond",
        "悪徳弁護士",
        "湖",
        "灰根",
        "灰根高太郎",
        "Yanni Yogi",
        "Yogi",
        "管理人",
        "怜侍の父",
        "弁護士",
        "射殺",
        "狩魔に殺された",
        "怜侍",
        "御剣",
        "トラウマ",
        "父を殺した",
        "地震",
        "銃",
        "多田敷",
        "多田敷道夫",
        "Bruce Goodman",
        "Goodman",
        "刑事",
        "宝月巴",
        "宝月",
        "Lana Skye",
        "Lana",
        "検事正",
        "巌徒",
        "巌徒海慈",
        "Damon Gant",
        "Gant",
        "署長",
        "警察署長",
        "SL-9",
        "SL9",
        "2年前",
        "証拠改ざん",
        "罪門直斗",
        "罪門",
        "Neil Marshall",
        "Neil",
        "青影",
        "青影丈",
        "Joe Darke",
        "Darke",
        "連続殺人犯",
        "宝月茜",
        "Ema Skye",
        "Ema",
        "科学捜査",
        "霊",
        "真宵から千尋",
        "Edgeworth",
        "協力",
        "改心",
        "変わった",
        "未解決事件",
        "御剣の過去",
        "因縁",
        "宿敵",
        "弟子",
        "助手",
        "パートナー",
        "綾里事務所"
      ]
    },
    "expected": null
  },
  {
    "name": "カナ正規化: ひらがな揺れ",
    "input": {
      "text": "やまのって誰",
      "keywords": [
        "高日",
        "高日美佳",
        "Cindy Stone",
        "Cindy",
        "被害者",
        "山野",
        "山野星雄",
        "Frank Sahwit",
        "Sahwit",
        "犯人",
        "綾里千尋",
        "千尋",
        "Mia Fey",
        "Mia",
        "死んだ",
        "殺された",
        "小中",
        "小中大",
        "Redd White",
        "ブルーコープ",
        "Bluecorp",
        "綾里真宵",
        "真宵",
        "Maya Fey",
        "Maya",
        "逮捕",
        "容疑者",
        "口寄せ",
        "霊媒",
        "霊術",
        "channeling",
        "spirit channeling",
        "千尋を呼ぶ",
        "荷星",
        "荷星三郎",
        "Will Powers",
        "トノサマン",
        "被告",
        "衣袋",
        "衣袋武志",
        "Jack Hammer",
        "Hammer",
        "元俳優",
        "姫神",
        "姫神サクラ",
        "Dee Vasquez",
        "プロデューサー",
        "マフィア",
        "5年前",
        "事故",
        "スタジオ",
        "グローバルスタジオ",
        "Global Studios",
        "狩魔",
        "狩魔豪",
        "Manfred von Karma",
        "von Karma",
        "フォン・カルマ",
        "DL-6",
        "DL6",
        "15年前",
        "真相",
        "御剣信",
        "Gregory Edgeworth",
        "エレベーター",
        "生倉",
        "生倉雪夫",
        "Robert Hammond",
        "Hammond",
        "悪徳弁護士",
        "湖",
        "灰根",
        "灰根高太郎",
        "Yanni Yogi",
        "Yogi",
        "管理人",
        "怜侍の父",
        "弁護士",
        "射殺",
        "狩魔に殺された",
        "怜侍",
        "御剣",
        "トラウマ",
        "父を殺した",
        "地震",
        "銃",
        "多田敷",
        "多田敷道夫",
        "Bruce Goodman",
        "Goodman",
        "刑事",
        "宝月巴",
        "宝月",
        "Lana Skye",
        "Lana",
        "検事正",
        "巌徒",
        "巌徒海慈",
        "Damon Gant",
        "Gant",
        "署長",
        "警察署長",
        "SL-9",
        "SL9",
        "2年前",
        "証拠改ざん",
        "罪門直斗",
        "罪門",
        "Neil Marshall",
        "Neil",
        "青影",
        "青影丈",
        "Joe Darke",
        "Darke",
        "連続殺人犯",
        "宝月茜",
        "Ema Skye",
        "Ema",
        "科学捜査",
        "霊",
        "真宵から千尋",
        "Edgeworth",
        "協力",
        "改心",
        "変わった",
        "未解決事件",
        "御剣の過去",
        "因縁",
        "宿敵",
        "弟子",
        "助手",
        "パートナー",
        "綾里事務所"
      ]
    },
    "expected": null
  }
];

// ─── G. buildKeywordSet ──────────────────────────────────────────────
export interface BuildKeywordSetFixture {
  name: string;
  input: { gameId: string; filterMode: 'strict' | 'standard' | 'lenient' | 'off'; progress?: { progressModel: 'chapter' | 'event'; currentChapterId?: string; completedEventIds?: string[] } };
  /** sorted ascending */
  expected: string[];
}

export const BUILD_KEYWORD_SET_FIXTURES: BuildKeywordSetFixture[] = [
  {
    "name": "ace-attorney-1, standard, ch1",
    "input": {
      "gameId": "ace-attorney-1",
      "filterMode": "standard",
      "progress": {
        "progressModel": "chapter",
        "currentChapterId": "ch1"
      }
    },
    "expected": [
      "15年前",
      "2年前",
      "5年前",
      "Bluecorp",
      "Bruce Goodman",
      "Cindy",
      "Cindy Stone",
      "DL-6",
      "DL6",
      "Damon Gant",
      "Darke",
      "Dee Vasquez",
      "Edgeworth",
      "Ema",
      "Ema Skye",
      "Frank Sahwit",
      "Gant",
      "Global Studios",
      "Goodman",
      "Gregory Edgeworth",
      "Hammer",
      "Hammond",
      "Jack Hammer",
      "Joe Darke",
      "Lana",
      "Lana Skye",
      "Manfred von Karma",
      "Maya",
      "Maya Fey",
      "Mia",
      "Mia Fey",
      "Neil",
      "Neil Marshall",
      "Redd White",
      "Robert Hammond",
      "SL-9",
      "SL9",
      "Sahwit",
      "Will Powers",
      "Yanni Yogi",
      "Yogi",
      "channeling",
      "spirit channeling",
      "von Karma",
      "エレベーター",
      "グローバルスタジオ",
      "スタジオ",
      "トノサマン",
      "トラウマ",
      "パートナー",
      "フォン・カルマ",
      "ブルーコープ",
      "プロデューサー",
      "マフィア",
      "事故",
      "元俳優",
      "刑事",
      "助手",
      "千尋",
      "千尋を呼ぶ",
      "協力",
      "口寄せ",
      "因縁",
      "地震",
      "変わった",
      "多田敷",
      "多田敷道夫",
      "姫神",
      "姫神サクラ",
      "宝月",
      "宝月巴",
      "宝月茜",
      "容疑者",
      "宿敵",
      "射殺",
      "小中",
      "小中大",
      "山野",
      "山野星雄",
      "巌徒",
      "巌徒海慈",
      "弁護士",
      "弟子",
      "御剣",
      "御剣の過去",
      "御剣信",
      "怜侍",
      "怜侍の父",
      "悪徳弁護士",
      "改心",
      "未解決事件",
      "検事正",
      "死んだ",
      "殺された",
      "湖",
      "灰根",
      "灰根高太郎",
      "父を殺した",
      "犯人",
      "狩魔",
      "狩魔に殺された",
      "狩魔豪",
      "生倉",
      "生倉雪夫",
      "真宵",
      "真宵から千尋",
      "真相",
      "科学捜査",
      "管理人",
      "綾里事務所",
      "綾里千尋",
      "綾里真宵",
      "罪門",
      "罪門直斗",
      "署長",
      "荷星",
      "荷星三郎",
      "衣袋",
      "衣袋武志",
      "被告",
      "被害者",
      "証拠改ざん",
      "警察署長",
      "連続殺人犯",
      "逮捕",
      "銃",
      "霊",
      "霊媒",
      "霊術",
      "青影",
      "青影丈",
      "高日",
      "高日美佳"
    ]
  },
  {
    "name": "ace-attorney-1, standard, ch3",
    "input": {
      "gameId": "ace-attorney-1",
      "filterMode": "standard",
      "progress": {
        "progressModel": "chapter",
        "currentChapterId": "ch3"
      }
    },
    "expected": [
      "15年前",
      "2年前",
      "5年前",
      "Bruce Goodman",
      "DL-6",
      "DL6",
      "Damon Gant",
      "Darke",
      "Dee Vasquez",
      "Edgeworth",
      "Ema",
      "Ema Skye",
      "Gant",
      "Global Studios",
      "Goodman",
      "Gregory Edgeworth",
      "Hammer",
      "Hammond",
      "Jack Hammer",
      "Joe Darke",
      "Lana",
      "Lana Skye",
      "Manfred von Karma",
      "Maya",
      "Mia",
      "Neil",
      "Neil Marshall",
      "Robert Hammond",
      "SL-9",
      "SL9",
      "Will Powers",
      "Yanni Yogi",
      "Yogi",
      "spirit channeling",
      "von Karma",
      "エレベーター",
      "グローバルスタジオ",
      "スタジオ",
      "トノサマン",
      "トラウマ",
      "パートナー",
      "フォン・カルマ",
      "プロデューサー",
      "マフィア",
      "事故",
      "元俳優",
      "刑事",
      "助手",
      "千尋",
      "協力",
      "口寄せ",
      "因縁",
      "地震",
      "変わった",
      "多田敷",
      "多田敷道夫",
      "姫神",
      "姫神サクラ",
      "宝月",
      "宝月巴",
      "宝月茜",
      "宿敵",
      "射殺",
      "巌徒",
      "巌徒海慈",
      "弁護士",
      "弟子",
      "御剣",
      "御剣の過去",
      "御剣信",
      "怜侍",
      "怜侍の父",
      "悪徳弁護士",
      "改心",
      "未解決事件",
      "検事正",
      "殺された",
      "湖",
      "灰根",
      "灰根高太郎",
      "父を殺した",
      "犯人",
      "狩魔",
      "狩魔に殺された",
      "狩魔豪",
      "生倉",
      "生倉雪夫",
      "真宵",
      "真宵から千尋",
      "真相",
      "科学捜査",
      "管理人",
      "綾里事務所",
      "罪門",
      "罪門直斗",
      "署長",
      "荷星",
      "荷星三郎",
      "衣袋",
      "衣袋武志",
      "被告",
      "被害者",
      "証拠改ざん",
      "警察署長",
      "連続殺人犯",
      "銃",
      "霊",
      "青影",
      "青影丈"
    ]
  },
  {
    "name": "ace-attorney-1, standard, ch5",
    "input": {
      "gameId": "ace-attorney-1",
      "filterMode": "standard",
      "progress": {
        "progressModel": "chapter",
        "currentChapterId": "ch5"
      }
    },
    "expected": [
      "15年前",
      "2年前",
      "Bruce Goodman",
      "DL-6",
      "DL6",
      "Damon Gant",
      "Darke",
      "Edgeworth",
      "Ema",
      "Ema Skye",
      "Gant",
      "Goodman",
      "Joe Darke",
      "Lana",
      "Lana Skye",
      "Maya",
      "Mia",
      "Neil",
      "Neil Marshall",
      "SL-9",
      "SL9",
      "spirit channeling",
      "von Karma",
      "パートナー",
      "刑事",
      "助手",
      "千尋",
      "協力",
      "口寄せ",
      "因縁",
      "変わった",
      "多田敷",
      "多田敷道夫",
      "宝月",
      "宝月巴",
      "宝月茜",
      "宿敵",
      "巌徒",
      "巌徒海慈",
      "弟子",
      "御剣",
      "御剣の過去",
      "怜侍",
      "改心",
      "未解決事件",
      "検事正",
      "殺された",
      "犯人",
      "狩魔",
      "狩魔豪",
      "真宵",
      "真宵から千尋",
      "真相",
      "科学捜査",
      "綾里事務所",
      "罪門",
      "罪門直斗",
      "署長",
      "被告",
      "被害者",
      "証拠改ざん",
      "警察署長",
      "連続殺人犯",
      "霊",
      "青影",
      "青影丈"
    ]
  },
  {
    "name": "ace-attorney-1, strict, ch1",
    "input": {
      "gameId": "ace-attorney-1",
      "filterMode": "strict",
      "progress": {
        "progressModel": "chapter",
        "currentChapterId": "ch1"
      }
    },
    "expected": [
      "15年前",
      "2年前",
      "5年前",
      "Bluecorp",
      "Bruce Goodman",
      "Cindy",
      "Cindy Stone",
      "DL-6",
      "DL6",
      "Damon Gant",
      "Darke",
      "Dee Vasquez",
      "Edgeworth",
      "Ema",
      "Ema Skye",
      "Frank Sahwit",
      "Gant",
      "Global Studios",
      "Goodman",
      "Gregory Edgeworth",
      "Hammer",
      "Hammond",
      "Jack Hammer",
      "Joe Darke",
      "Lana",
      "Lana Skye",
      "Manfred von Karma",
      "Maya",
      "Maya Fey",
      "Mia",
      "Mia Fey",
      "Neil",
      "Neil Marshall",
      "Redd White",
      "Robert Hammond",
      "SL-9",
      "SL9",
      "Sahwit",
      "Will Powers",
      "Yanni Yogi",
      "Yogi",
      "channeling",
      "clock",
      "spirit channeling",
      "von Karma",
      "エレベーター",
      "グローバルスタジオ",
      "スタジオ",
      "トノサマン",
      "トラウマ",
      "パートナー",
      "フォン・カルマ",
      "ブルーコープ",
      "プロデューサー",
      "マフィア",
      "事故",
      "元俳優",
      "凶器",
      "刑事",
      "助手",
      "千尋",
      "千尋を呼ぶ",
      "協力",
      "口寄せ",
      "因縁",
      "地震",
      "変わった",
      "多田敷",
      "多田敷道夫",
      "姫神",
      "姫神サクラ",
      "宝月",
      "宝月巴",
      "宝月茜",
      "容疑者",
      "宿敵",
      "射殺",
      "小中",
      "小中大",
      "山野",
      "山野星雄",
      "巌徒",
      "巌徒海慈",
      "弁護士",
      "弟子",
      "御剣",
      "御剣の過去",
      "御剣信",
      "怜侍",
      "怜侍の父",
      "悪徳弁護士",
      "改心",
      "時計",
      "未解決事件",
      "検事正",
      "死んだ",
      "殺された",
      "湖",
      "灰根",
      "灰根高太郎",
      "父を殺した",
      "犯人",
      "狩魔",
      "狩魔に殺された",
      "狩魔豪",
      "生倉",
      "生倉雪夫",
      "真宵",
      "真宵から千尋",
      "真相",
      "科学捜査",
      "管理人",
      "綾里事務所",
      "綾里千尋",
      "綾里真宵",
      "罪門",
      "罪門直斗",
      "置き時計",
      "署長",
      "荷星",
      "荷星三郎",
      "衣袋",
      "衣袋武志",
      "被告",
      "被害者",
      "証拠改ざん",
      "警察署長",
      "連続殺人犯",
      "逮捕",
      "銃",
      "霊",
      "霊媒",
      "霊術",
      "青影",
      "青影丈",
      "高日",
      "高日美佳"
    ]
  },
  {
    "name": "ace-attorney-1, lenient, ch1",
    "input": {
      "gameId": "ace-attorney-1",
      "filterMode": "lenient",
      "progress": {
        "progressModel": "chapter",
        "currentChapterId": "ch1"
      }
    },
    "expected": [
      "15年前",
      "2年前",
      "Bluecorp",
      "Bruce Goodman",
      "Cindy",
      "Cindy Stone",
      "DL-6",
      "DL6",
      "Damon Gant",
      "Darke",
      "Dee Vasquez",
      "Ema",
      "Ema Skye",
      "Frank Sahwit",
      "Gant",
      "Goodman",
      "Gregory Edgeworth",
      "Hammer",
      "Hammond",
      "Jack Hammer",
      "Joe Darke",
      "Lana",
      "Lana Skye",
      "Manfred von Karma",
      "Mia",
      "Mia Fey",
      "Neil",
      "Neil Marshall",
      "Redd White",
      "Robert Hammond",
      "SL-9",
      "SL9",
      "Sahwit",
      "Yanni Yogi",
      "Yogi",
      "von Karma",
      "エレベーター",
      "トノサマン",
      "トラウマ",
      "フォン・カルマ",
      "ブルーコープ",
      "プロデューサー",
      "マフィア",
      "元俳優",
      "刑事",
      "千尋",
      "地震",
      "多田敷",
      "多田敷道夫",
      "姫神",
      "姫神サクラ",
      "宝月",
      "宝月巴",
      "宝月茜",
      "射殺",
      "小中",
      "小中大",
      "山野",
      "山野星雄",
      "巌徒",
      "巌徒海慈",
      "弁護士",
      "御剣",
      "御剣信",
      "怜侍",
      "怜侍の父",
      "悪徳弁護士",
      "検事正",
      "死んだ",
      "殺された",
      "湖",
      "灰根",
      "灰根高太郎",
      "父を殺した",
      "犯人",
      "狩魔",
      "狩魔に殺された",
      "狩魔豪",
      "生倉",
      "生倉雪夫",
      "真相",
      "科学捜査",
      "管理人",
      "綾里千尋",
      "罪門",
      "罪門直斗",
      "署長",
      "衣袋",
      "衣袋武志",
      "被告",
      "被害者",
      "証拠改ざん",
      "警察署長",
      "連続殺人犯",
      "銃",
      "青影",
      "青影丈",
      "高日",
      "高日美佳"
    ]
  },
  {
    "name": "未知のゲームID → 空集合",
    "input": {
      "gameId": "unknown-game",
      "filterMode": "standard"
    },
    "expected": []
  }
];

// ─── H. buildDescriptionPhraseSet ────────────────────────────────────
export interface BuildDescriptionPhraseSetFixture {
  name: string;
  input: { gameId: string };
  /** sorted ascending */
  expected: string[];
}

export const BUILD_DESCRIPTION_PHRASE_SET_FIXTURES: BuildDescriptionPhraseSetFixture[] = [
  {
    "name": "ace-attorney-1: 全フレーズ抽出",
    "input": {
      "gameId": "ace-attorney-1"
    },
    "expected": [
      "DL-6",
      "DL-6号事件",
      "SL-9号事件"
    ]
  },
  {
    "name": "未知のゲームID → 空集合",
    "input": {
      "gameId": "unknown-game"
    },
    "expected": []
  },
  {
    "name": "空文字 ID → 空集合",
    "input": {
      "gameId": ""
    },
    "expected": []
  }
];
